# Generated by Django 3.2.8 on 2021-11-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
